language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
# command to install dependencies
install:
  - python setup.py -q install
# command to run tests
script: python -m unittest test.tests
